import assert from 'node:assert/strict'
import { describe, it } from 'node:test'
import { calculateWbMetrics } from './wb-calculator.js'

describe('WB backend metrics calculator', () => {
  it('matches frontend tax and net profit formulas', () => {
    const result = calculateWbMetrics({
      rows: [
        {
          article: 'SKU-1',
          documentType: '',
          reason: 'Продажа',
          salesDate: '01.05.2026',
          salesMethod: '',
          warehouse: '',
          basketId: '',
          srid: '',
          logisticsKind: '',
          quantity: 2,
          returnCount: 0,
          deliveryCount: 0,
          retailPrice: 1000,
          retailPriceWithDiscount: 900,
          retailAmount: 850,
          payout: 700,
          logisticsCost: 0,
          wbCommissionRate: 10,
          wbCommission: 0,
          paymentServicesCommission: 0,
          pvzCompensation: 0,
          transportReimbursement: 0,
          storageCost: 0,
          withholdings: 0,
          acceptanceOperations: 0,
          fines: 0,
          vvCorrection: 0,
          loyaltyCompensation: 0,
          loyaltyProgramCost: 0,
          loyaltyPointsWithheld: 0,
        },
        {
          article: 'SKU-1',
          documentType: '',
          reason: 'Логистика',
          salesDate: '01.05.2026',
          salesMethod: '',
          warehouse: '',
          basketId: '',
          srid: '',
          logisticsKind: '',
          quantity: 0,
          returnCount: 0,
          deliveryCount: 0,
          retailPrice: 0,
          retailPriceWithDiscount: 0,
          retailAmount: 0,
          payout: 0,
          logisticsCost: 100,
          wbCommissionRate: 0,
          wbCommission: 0,
          paymentServicesCommission: 0,
          pvzCompensation: 0,
          transportReimbursement: 0,
          storageCost: 0,
          withholdings: 0,
          acceptanceOperations: 0,
          fines: 0,
          vvCorrection: 0,
          loyaltyCompensation: 0,
          loyaltyProgramCost: 0,
          loyaltyPointsWithheld: 0,
        },
      ],
      filters: {
        articlePattern: '*',
        excludeArticlePattern: false,
        priceMin: null,
        priceMax: null,
      },
      params: {
        vatRatePercent: 5,
        taxRatePercent: 6,
        cogsMatchingMode: 'full',
      },
      costByKey: new Map([['full:sku-1', 100]]),
    })

    assert.equal(result.cells.revenueBeforeSpp, 900)
    assert.equal(result.cells.transferToBank, 600)
    assert.equal(result.cells.cogs, 200)
    assert.equal(result.cells.taxAmount, 99)
    assert.equal(result.cells.netProfit, 301)
    assert.equal(result.cells.salesBase, 790)
  })

  it('splits sales scheme by shared fbs/fbm fulfillment semantics and linked rows', () => {
    const result = calculateWbMetrics({
      rows: [
        {
          article: 'SKU-FBS',
          documentType: '',
          reason: 'Продажа',
          salesDate: '01.05.2026',
          salesMethod: '',
          warehouse: '',
          basketId: '',
          srid: 'srid-fbs',
          logisticsKind: '',
          quantity: 1,
          returnCount: 0,
          deliveryCount: 0,
          retailPrice: 1000,
          retailPriceWithDiscount: 900,
          retailAmount: 850,
          payout: 700,
          logisticsCost: 0,
          wbCommissionRate: 0,
          wbCommission: 0,
          paymentServicesCommission: 0,
          pvzCompensation: 0,
          transportReimbursement: 0,
          storageCost: 0,
          withholdings: 0,
          acceptanceOperations: 0,
          fines: 0,
          vvCorrection: 0,
          loyaltyCompensation: 0,
          loyaltyProgramCost: 0,
          loyaltyPointsWithheld: 0,
        },
        {
          article: 'SKU-FBS',
          documentType: '',
          reason: 'Логистика',
          salesDate: '01.05.2026',
          salesMethod: 'FBS',
          warehouse: '',
          basketId: '',
          srid: 'srid-fbs',
          logisticsKind: '',
          quantity: 0,
          returnCount: 0,
          deliveryCount: 0,
          retailPrice: 0,
          retailPriceWithDiscount: 0,
          retailAmount: 0,
          payout: 0,
          logisticsCost: 0,
          wbCommissionRate: 0,
          wbCommission: 0,
          paymentServicesCommission: 0,
          pvzCompensation: 0,
          transportReimbursement: 0,
          storageCost: 0,
          withholdings: 0,
          acceptanceOperations: 0,
          fines: 0,
          vvCorrection: 0,
          loyaltyCompensation: 0,
          loyaltyProgramCost: 0,
          loyaltyPointsWithheld: 0,
        },
        {
          article: 'SKU-FBM',
          documentType: '',
          reason: 'Продажа',
          salesDate: '01.05.2026',
          salesMethod: 'FBW',
          warehouse: '',
          basketId: '',
          srid: 'srid-fbm',
          logisticsKind: '',
          quantity: 1,
          returnCount: 0,
          deliveryCount: 0,
          retailPrice: 2000,
          retailPriceWithDiscount: 1800,
          retailAmount: 1700,
          payout: 1400,
          logisticsCost: 0,
          wbCommissionRate: 0,
          wbCommission: 0,
          paymentServicesCommission: 0,
          pvzCompensation: 0,
          transportReimbursement: 0,
          storageCost: 0,
          withholdings: 0,
          acceptanceOperations: 0,
          fines: 0,
          vvCorrection: 0,
          loyaltyCompensation: 0,
          loyaltyProgramCost: 0,
          loyaltyPointsWithheld: 0,
        },
      ],
      filters: {
        articlePattern: '*',
        excludeArticlePattern: false,
        priceMin: null,
        priceMax: null,
      },
      params: {
        vatRatePercent: 5,
        taxRatePercent: 6,
        cogsMatchingMode: 'full',
      },
      costByKey: new Map(),
    })

    assert.deepEqual(result.breakdowns.salesScheme, [
      { label: 'FBS — склад продавца', value: 1000 },
      { label: 'FBW — склад ВБ', value: 2000 },
    ])
  })
})
